### PR TITLE
Added launch and python files to synchronize gazebo and moveit  

### PR DESCRIPTION
**Pull request by beatrizleon**
To run it simply launch gazebo and rviz with moveit first, and then:
roslaunch gazebo2rviz gazebo2moveit.launch 

This is a video of how it looks like:
https://www.opentest.co/share/1a263980908d11e6b41c97aa6b0c5ccc

Some meshes still don't look good (e.g. coke_can) but this drill works ok and all geometries

### CODE REVIEW

**Comment by andreasBihlmaier** [comment]
Thanks for your work.

I'll try to test this as soon as I have some spare time. Unfortunately, pyassimp has several issues on Ubuntu 16.04 + ROS Kinetic [1].

Some minor comments:
- Please add `<arg name="ignore_submodels_of" default="" />` to the launch file
- Please refactor common code between sdf2moveit and gazebo2moveit into a separate file.
- The COLLADA markers in rviz issue is a general one.

[1] After fixing https://bugs.launchpad.net/ubuntu/+source/assimp/+bug/1589949 and adapting module loading (https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_commander/src/moveit_commander/planning_scene_interface.py#L44), I run into

```
File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 306, in load                                                                                                                                                                                                                                                  
    model = _assimp_lib.load(filename.encode("ascii"), processing)                                                                                                                                                                                                                                                             
AttributeError: 'AssimpLib' object has no attribute 'load' 
```

which I have to investigate with more time available.

**Comment by beatrizleon** [comment]
Hi @andreasBihlmaier, sorry for the delay in reply.

I will do the changes you suggested.

About the assimp, would it be better to import the PlanningSceneInterface instead and load the mesh from there directly?

what do you mean with "The COLLADA markers in rviz issue is a general one"?

**Comment by beatrizleon** [comment]
@andreasBihlmaier I unified the functions for sdf2moveit and gazebo2moveit. Now the first one declares a class and the second one uses it and update the models. 

Also added launch files for both and renamed sdf2moveit_collision_node to include _node as the other files.

Let me know if you think it is ok

**Comment by andreasBihlmaier** [comment]
Hi @beatrizleon,
thanks for the further development.

Could you please rebase the branch to resolve the merge conflict?
I'll test your pull request then ASAP (on 14.04).

Regarding the COLLADA markers: The way in which resources are linked within .dae files poses issues for loading them in rviz. If you look into ~/.gazebo/models/coke_can/meshes/coke_can.dae and search for "texture0", you'll find `<init_from>../materials/textures/coke_can.png</init_from>`, which works for gazebo as there is  ~/.gazebo/models/coke_can/materials/textures/coke_can.png. However, rviz apparently bases the resolution of such linked resources on its current working directory.

Regarding the assimp issue, it would be great if you could try to directly use PlanningSceneInterface for loading the meshes.

Best,
Andreas

**Comment by beatrizleon** [comment]
@andreasBihlmaier I rebased and now the conflict is resolved. Could you please test on 14.04?

Thanks for the explanation for the collada markers.

Regarding the assimp issue, I believe the moveit developers also have same issue with Planning scene interface so I don't think we will solve the problem with that. However, in the link you send me (https://bugs.launchpad.net/ubuntu/+source/assimp/+bug/1589949) they seemed to have solved the problem so it should be released in 16.04 soon.

**Comment by andreasBihlmaier** [comment]
@beatrizleon @ethanfowler I'm interested to add the new MoveIt! functionality here, could one of you please rebase the merge request to ease testing (melodic on bionic) for me?

**Comment by beatrizleon** [comment]
yes @andreasBihlmaier, it would be great to have this integrated in your repository so we don't have to use our fork. We can rebase, merge and test but only on kinetic, would that work for you?

**Comment by andreasBihlmaier** [comment]
I close this pull request for now as things have diverged too far.
Looking at https://github.com/shadow-robot/gazebo2rviz/tree/noetic-devel there seems to be recent activity in the shadow-robot fork.
Furthermore, https://github.com/andreasBihlmaier/gazebo2rviz/network indicates at least https://github.com/ANYbotics/gazebo2rviz and https://github.com/barryridge/gazebo2rviz as other good candidates for a pull request.

@biofotis @barryridge @remod / @pleemann anyone interested in creating a fresh pull request to your latest gazebo2rviz branch?

**Comment by remod** [comment]
We stopped using `gazebo2rviz` recently and I just archived our fork, thanks for checking though.

**Comment by barryridge** [comment]
@andreasBihlmaier I'll try to submit a PR when I can soon - my fork just needs a bit of polishing/improvement, but I've become a bit busy with other tasks of recent.

**Pull request closed without merging**
