### PR TITLE
Fixed displaying of multiple visual/collision elements per link.

### PR DESCRIPTION
**Pull request by peci1**
The moveit part remains untested. Can you give it a try with your examples?

Solves #4, requires on andreasBihlmaier/pysdf#4 .

### CODE REVIEW

**Comment by peci1** [comment]
I also needed to change the Marker message namespaces for the collisions/visuals. Hope it doesn't break any existing usage.

**Comment by beatrizleon** [comment]
I tested both PRs and now it looks ok:
image

hope it gets merged soon :)

I am now trying to have same functionality but instead of markers, with collision objects. So far I managed with simple privitives but with this I think should be possible with mesh too. I will create a pr soon.

**Comment by beatrizleon** [comment]
Here is my new pr: https://github.com/andreasBihlmaier/gazebo2rviz/pull/6. It will need this one to be merged for it to work

**Comment by peci1** [comment]
@beatrizleon nice to see I've helped you :) However, I can't test your PR, because I don't use Moveit at all...

What's wrong with the coke can mesh?

**Comment by andreasBihlmaier** [comment]
See https://github.com/andreasBihlmaier/pysdf/pull/4#issuecomment-253995157

**Pull request merged**
